Repository Clueless-Community/scrape-up, pull requests merged in 2023-05, with the labels that each got.

#178 Update contribution.md
  contribution.md
Labels: GSSOC23

#182 added error handling statements and test for instagram
  .vscode/settings.json
  src/scrape_up/instagram/users.py
  src/test/instagram_test.py
Labels: gssoc23, level3

#194 Created a Post function in Instagram's User.py for accessing the users …
  src/scrape_up/instagram/users.py
Labels: gssoc23, level2
