Repository Clueless-Community/scrape-up, pull requests merged in 2023-07, with the labels that each got.

#421 Dev Community
  documentation.md
  src/scrape_up/devCommunity/__init__.py
  src/scrape_up/devCommunity/articles.py
Labels: under review

#412 Scrape up Spotify
  documentation.md
  src/scrape_up/spotify/__init__.py
  src/scrape_up/spotify/spotify_file.py
Labels: under review

#403 Times jobs
  documentation.md
  src/scrape_up/TImesJobs/__init__.py
  src/scrape_up/TImesJobs/timesjobs_scraper.py
Labels: gssoc23, under review

#388 flipkart scraping of mobile phone under 50k
  documentation.md
  src/scrape_up/flipkart/flipkart_file.py
Labels: under review

#445 Added Top_stories method to GoogleNews Class
  documentation.md
  src/scrape_up/googleNews/googleNews.py
Labels: under review

#468 Added CovidInfo Project
  dev-documentation.md
  src/scrape_up/CovidInfo/__init__.py
  src/scrape_up/CovidInfo/covid_info.py
Labels: gssoc23, under review

#471 Added Flipkart t-shirt scrapper
  dev-documentation.md
  src/scrape_up/flipkart/__init__.py
  src/scrape_up/flipkart/flipkart_clothing.py
  src/scrape_up/flipkart/flipkart_file.py
Labels: gssoc23

#383 News scraping
  .github/PULL_REQUEST_TEMPLATE/scrap-bcc-news.py
  src/scrape_up/BBCNews/__init__.py
  src/scrape_up/BBCNews/bbc_news.py
Labels: under review

#352 Implemented BCC News scraping module
  .github/PULL_REQUEST_TEMPLATE/scrap-bcc-news.py
Labels: under review

#506 Added getDinnerWith50PercentOff() Method
  dev-documentation.md
  src/scrape_up/eazydiner/eazydiner.py
Labels: gssoc23, under review

#496 Added Flyrobu and Robu search
  dev-documentation.md
  src/scrape_up/Robu/__init__.py
  src/scrape_up/Robu/robu.py
  src/scrape_up/flyrobu/__init__.py
  src/scrape_up/flyrobu/flyrobu.py
Labels: gssoc23, under review

#480 Added Mediline's Medical Encyclopedia scraper
  dev-documentation.md
  src/scrape_up/MediEncyclopedia/__init__.py
  src/scrape_up/MediEncyclopedia/mediencyclopedia.py
Labels: gssoc23, under review

#521 ICC rankings script added
  dev-documentation.md
  src/scrape_up/icc/__init__.py
  src/scrape_up/icc/icc_rankings.py
Labels: gssoc23, under review

#542 UCI Scrapper
  dev-documentation.md
  src/scrape_up/UCI/UCI.py
  src/scrape_up/UCI/__init__.py
Labels: gssoc23, level3

#533 Add Method to Retrieve Detailed Product Description and Specification
  dev-documentation.md
  src/scrape_up/flyrobu/flyrobu.py
Labels: gssoc23, under review

#577 updated get_feed() function in Hashnode Scraper
  dev-documentation.md
  src/scrape_up/hashnode/hashnode.py
Labels: gssoc23, under review
