Repository Clueless-Community/scrape-up, pull requests merged in 2023-10, with the labels that each got.

#777 Made changes in dev community module.
  src/scrape_up/devCommunity/__init__.py
Labels: enhancement, hacktoberfest

#791 88x31 banner scrapper
  dev-documentation.md
  src/scrape_up/banner88x31/__init__.py
  src/scrape_up/banner88x31/scraper88x31.py
Labels: under review

#790 Fixed codeforces module
  dev-documentation.md
  src/scrape_up/codeforces/user.py
Labels: under review

#840 test: Adding tests for hackerearth module
  src/test/hackerearth_test.py
Labels: hacktoberfest

#835 Unit Test: Added Flyrobu test file
  src/test/flyrobu_test.py
Labels: under review

#845 Scraping Dictionarycom for the Word of the Day
  dev-documentation.md
  src/scrape_up/dictionary/__init__.py
  src/scrape_up/dictionary/wordoftheday.py
Labels: under review
